### ISSUE TITLE
Define '.ajax_loader' in 'style.css'

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/login-report#13]
We need to define the following within `style.css`:

``` css
...
.ajax_loader {
  background: url('../img/loading.gif') no-repeat center center transparent;
  background-size:90px 90px;
  width:100%; height:100%;
}
```
